site_name: Travelar - Plataforma de Hospedagem
site_url: 
repo_url:
repo_name: Github

theme:
  name: material
  language: pt-BR
  palette: 
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro
  features:
    - navigation.tabs 
    - navigation.sections
    - navigation.expand

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

nav:
  - Início: index.md
  - Planejamento:
    - Backlog: planejamento/backlog.md
    - Diagramas: planejamento/diagramas.md
  - Design & UX:
    - Protótipo: design/prototipo.md
  - Arquitetura:
    - API de Autenticação: arquitetura/api-auth.md
    - Backend: arquitetura/backend.md
    - Frontend: arquitetura/frontend.md
  - Banco de Dados:
    - Modelagem: dados/banco-de-dados.md
